# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnclist < Formula
    desc ""
    homepage "https://github.com/keyglee/dnc-list-search"
    version "0.0.9"
  
    on_macos do
      url "https://github.com/keyglee/dnc-list-search/releases/download/v0.0.9/dnc-list-search_0.0.9_darwin_all.tar.gz"
      sha256 "2677a8c4713f50ca3a23924021fbdd284f6812c6a0b9f5454272b2ddb31b94e6"
  
      def install
        bin.install "dnclist"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/keyglee/dnc-list-search/releases/download/v0.0.9/dnc-list-search_0.0.9_linux_amd64.tar.gz"
        sha256 "3f026adc04b3fb1c769358323bbf2f8e27462d5178ffec6eefbcc299369283de"
  
        def install
          bin.install "dnclist"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/keyglee/dnc-list-search/releases/download/v0.0.9/dnc-list-search_0.0.9_linux_arm64.tar.gz"
        sha256 "0018d8a076fe7e37e842aca550c842716c36d168d3d7aad67f4f95e9b40f3fe9"
  
        def install
          bin.install "dnclist"
        end
      end
    end
  end
