# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnclistsearch < Formula
    desc ""
    homepage "https://github.com/keyglee/dnclistsearch"
    version "0.1.1"
  
    on_macos do
      url "https://github.com/keyglee/dnclistsearch/releases/download/v0.1.1/dnclistsearch_0.1.1_darwin_all.tar.gz"
      sha256 "c21d732be3ffc34f987024c435ed90cc6cb9cbc69559ceb4260aa4873f265452"
  
      def install
        bin.install "dnclistsearch"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/keyglee/dnclistsearch/releases/download/v0.1.1/dnclistsearch_0.1.1_linux_amd64.tar.gz"
        sha256 "169340b616774213b9fce0a163e0194ba22e5c39b24aeaa199b56d0e401a854c"
  
        def install
          bin.install "dnclistsearch"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/keyglee/dnclistsearch/releases/download/v0.1.1/dnclistsearch_0.1.1_linux_arm64.tar.gz"
        sha256 "ddfabef81abb2fd491788b6b5451d1ad2d43aa12a8b798951df16a98051d48db"
  
        def install
          bin.install "dnclistsearch"
        end
      end
    end
  end
