# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnclistsearch < Formula
    desc ""
    homepage "https://github.com/keyglee/dnclistsearch"
    version "0.1.0"
  
    on_macos do
      url "https://github.com/keyglee/dnclistsearch/releases/download/v0.1.0/dnclistsearch_0.1.0_darwin_all.tar.gz"
      sha256 "4181fed7d6ad8143343397ed03a5a1af21acea32e0d57b6db17bf1bd628e725d"
  
      def install
        bin.install "dnclistsearch"
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/keyglee/dnclistsearch/releases/download/v0.1.0/dnclistsearch_0.1.0_linux_amd64.tar.gz"
        sha256 "2211cee5ddaa34a7a9abcde658c813b135a15222b1f3733089fcf18bed52c50f"
  
        def install
          bin.install "dnclistsearch"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/keyglee/dnclistsearch/releases/download/v0.1.0/dnclistsearch_0.1.0_linux_arm64.tar.gz"
        sha256 "4898bf791b80dae2f08991f7de8a60a09fd6e69bd64b8c8c8d94845fa2627d04"
  
        def install
          bin.install "dnclistsearch"
        end
      end
    end
  end

4181fed7d6ad8143343397ed03a5a1af21acea32e0d57b6db17bf1bd628e725d  dnclistsearch_0.1.0_darwin_all.tar.gz
2211cee5ddaa34a7a9abcde658c813b135a15222b1f3733089fcf18bed52c50f  dnclistsearch_0.1.0_linux_amd64.tar.gz
4898bf791b80dae2f08991f7de8a60a09fd6e69bd64b8c8c8d94845fa2627d04  dnclistsearch_0.1.0_linux_arm64.tar.gz